### ISSUE TITLE
GAMLSS code

### ISSUE THREAD

**Issue by cindyhfls** [sunlianglong/BrainChart-FC-Lifespan#1]
Hi, 

I could not find this file:
GAMLSS_ModelSelect_and_RunCentile.R

Would you be able to share this? Thank you!

Cindy

**Comment by sunlianglong** [comment]
Hi Cindy,

Sorry for the late response.

Over the past couple of months, we have updated our analysis strategy, and to avoid any potential misguidance, we removed some code files that underwent significant changes. We have now re-uploaded the relevant code files.

The main adjustment involves treating the site as a random effect within the GAMLSS framework to correct for site effects. We will also be updating our bioRxiv preprint shortly to include descriptions of these methodological adjustments.
